# config/schema/commerce_molpay_normal.schema.yml
commerce_payment.commerce_payment_gateway.plugin.molpay_normal:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    verify_key:
      type: string
      label: 'Verify Key'
    secret_key:
      type: string
      label: 'Secret Key'